dssg/triage

requirements_dev.txt, tests/example_schema.yaml, tests/test_schema.py, tox.ini, triage/schema.py
A working schema generator. I didn't include engine/connection binding in here, but that can be easily added in a future PR (it's really just metadata.create_all())
The idea is that we should be able to go from here and interface with collate fairly easily. Now that we know what different tables represent events, we should be able to create a bunch of SpacetimeAggregations with very little boilerplate. But since you know collate better, let me know if there's something missing here that's needed for that.
I'm not sure what to do with primary entity and outcome variable. I know code-wise, those will be important, but I'm not sure if/how their existence gets encoded into the database schema. More generally, are there other assumptions we should be making given that this is specifically for …
=> First pass at schema generator

requirements_dev.txt, tests/example_schema.yaml, tests/test_schema.py, tox.ini, triage/schema.py
Creating an indexed geometry column for any entity marked spatial, using GeoAlchemy2.
Also, psycopg2 was added (so I could see this work end to end), and I fixed something in tox that wasn't letting GeoAlchemy2 install.
=> Spatial column support

README.rst, tests/test_integration.py, tests/test_model_trainers.py, tests/test_predictors.py, tests/test_storage.py, tests/utils.py, triage/db.py, triage/model_group_stored_procedure.sql, triage/model_trainers.py, triage/predictors.py, triage/storage.py, triage/utils.py
- Implement Predictor class that generates predictions of a arbitrary set against a trained model
- Refactor ModelTrainer to adjust interface closer to what is useful for predictions
- Move routines shared between Predictor and ModelTrainer to triage.utils
- Create test.utils to hold utilities useful in tests
=> Dataset Predictor

tests/test_integration.py, tests/test_predictors.py, tests/test_scoring.py, tests/utils.py, triage/db.py, triage/scoring.py, triage/storage.py
Basic implementation of model scoring. Not all metrics are included, I tried to include the minimal possible to demonstrate a few well-needed features: thresholds, parameters, and custom (user-defined) metrics. My intention is for us to add more metrics in later, small pull requests.
- Add ModelScorer class to compute a configurable set of metrics on a trained model and set of predictions
- Fix Predictor test and update integration test to include evaluations
- Update fake_trained_model to use model storage engines
- Add InMemoryModelStorageEngine to enable simple usage of components that pass around a model
=> Evaluations (resolves #8)

example_experiment_config.yaml, requirements_dev.txt, tests/test_feature_generators.py, triage/feature_generators.py, triage/pipeline.py
- Modify constructor and generate in FeatureGenerator to allow the object to be reused
- Support new collate interface for Aggregates and SpacetimeAggregations
- Support new collate Categorical feature
=> Support new collate categorical interface [Resolves #15]

requirements.txt, tests/test_feature_generators.py, tests/test_label_generators.py, tests/test_pipeline.py, tests/test_predictors.py, triage/feature_generators.py, triage/label_generators.py, triage/pipeline.py, triage/predictors.py, triage/storage.py
- Remove old fake timechop functions from Pipeline, replace with imported timechop
- Modify Predictor to work with inspections-style multi-index
- Modify LabelGenerator to be BinaryLabelGenerator, use new expanded schema
- Short-circuit Scoring if new inspections-style multi-index is used, before implementation is decided
- Add integration test for Pipeline class
=> Incorporate Timechop [Resolves #29]

tests/test_feature_dictionary_creator.py, triage/feature_dictionary_creator.py, triage/features.py, triage/pipeline.py
- Add FeatureDictionaryCreator to create a feature dictionary from querying the features schema
- Add features module to make each features-related component more accessible
- Use new feature dictionary workflow in pipeline
=> Add Feature Dictionary Creator [Resolves #49]

triage/predictors.py
- Add nan check for label and insert null
=> Add NaN check for label [Resolves #42]

example_experiment_config.yaml
Adding some guidance to how the experiment config file works at present.
=> Add comments to example experiment config [Resolves #25]

triage/predictors.py
Computing rankings when there are daily predictions was always of dubious utility, and was done to conform to the Predictions schema at what seemed like a low cost. As it turns out, the code to subset these dataframes was very memory-hungry, so for now the cost for leaving those columns null seems to be lower.
Also, bulk_save_objects is used now because the scale of these predictions can get pretty big.
- Remove ranking code from multiple as_of_dates-in-matrix code branch
- Switch Predictions.write_to_db to bulk_save_objects
Although there could still potentially be a memory leak in the evaluations code, I think it's more likely that it was here. The code in evaluations is fairly simple, there is less work with large objects like dataframes, and fewer places for things to go wrong. It's …
=> Remove rankings per as_of_date if as_of_date is in index [Resolves #59]

example_experiment_config.yaml, tests/test_pipeline.py, triage/pipelines/local_parallel.py, triage/pipelines/serial.py
- Add model_comment parsing to both pipelines, passing to ModelTrainer
- Add model_comment example to example_experiment_config
=> Support model_comment [Resolves #75]

triage/db.py, triage/model_group_stored_procedure.sql, triage/model_trainers.py, triage/predictors.py
fixed brackets
change to model_config for model_groups for equivalence inside groups
added rounding to avoid underflow errors in postgres
=> Add model config to model groups and stored procedure

setup.py, tests/test_integration.py, tests/test_model_trainers.py, tests/test_pipeline.py, triage/db.py, triage/model_trainers.py, triage/pipelines/base.py, triage/pipelines/local_parallel.py, triage/pipelines/serial.py, triage/utils.py
- Add experiment table, foreign key in models table
- Add train_end_time to models table (auto-computed based on matrix metta-data)
=> Schema updates [Resolves #94]

tests/test_scoring.py
Turns out it didn't have a bug, but here's a test.
Also some PEP8 fixes.
=> Thresholding unit test [Resolves #71]

requirements.txt, requirements_dev.txt, tests/test_model_trainers.py, triage/model_trainers.py, triage/predictors.py, triage/scoring.py, triage/utils.py
- Add 'retrying' module
- Add db_retry decorator which wraps 'retrying' module retry with common arguments for db retries
- Use db_retry decorator in all database interactions in pipeline
=> Retry DB interactions [Resolves #151]

requirements.txt, requirements_dev.txt, tests/test_feature_generators.py, triage/feature_generators.py
- Parse array_categoricals as an aggregation, use Compare with array casting for choices
- Make sure collate master is installed
=> Support categoricals on array columns [Resolves #121]

README.md
I fixed collate' s link (It was broken)
=> Fixed broken link to collate

requirements.txt, triage/experiments/base.py
- Update architect to 0.2.1
- Bind experiment's beginning of time to FeatureGenerator
=> Support FeatureGenerator#beginning_of_time [Resolves #183]

triage/experiments/base.py
- Add log messages
- Introduce Experiment#master_feature_dictionary
=> Increase triage logging [Resolves #195]

example_experiment_config.yaml, requirements.txt, tests/test_experiments.py, triage/experiments/base.py, triage/experiments/multicore.py, triage/experiments/singlethreaded.py
- Update to new enough results_schema and catwalk to calculate and save individual importances
- Call catwalk.IndividualImportance after predictions
- Use new catwalk CSVMatrixStore
- Refactor Experiment's matrix store creation and make it configurable
=> Individual Importances [Resolves #217]

example_experiment_config.yaml
=> Describe an example of user_metadata use

README.md, requirements_dev.txt, triage/experiments/base.py
- Add mkdocs to requirements_dev
- Fix docstrings and README to work better with mkdocs
=> Initial mkdocs integration

requirements.txt, tests/test_experiments.py
- Update timechop pin to 0.1.5
- Update tests to expect timechop's new behavior
=> Update timechop [Resolves #237]

README.md
Thought this would be a good place to get started with the code.
Likely not how we'd like this to read; but, at least, a place to start.
=> improved README: completed trailing-off s—

docs/mkdocs.yml, docs/sources/experiments/features.md
A first pass at a format for feature recipes. Would like some feedback to see if this is how we want to structure feature writeups for a general audience.
=> Feature Generation Recipe Book [Resolves #416]

src/triage/experiments/validate.py
Fixes #408. Very simple fix. The user is responsable of the correct casting in the configuration file.
=> Fixes #408

src/tests/catwalk_tests/test_predictors.py, src/triage/component/catwalk/predictors.py
- Switches around some session opening/closing in Predictor object,
making sure all of the closes are in finally blocks
=> Clean up Session Closing in Predictor [Resolves #478]

docs/sources/experiments/running.md, src/triage/cli.py
- Add matrix storage configurability to CLI
- Add matrix storage configurability info to 'Running an Experiment' doc
=> Add HDF5 to CLI and doc [Resolves #496]

develop
s.t. tests -- which assume it's installed -- pass, for example
=> develop script should install triage with the rq extra

src/tests/collate_tests/test_from_obj.py, src/triage/component/collate/from_obj.py
- Fix method references in FromObj and update test
=> Fix FromObj.maybe_materialize [Resolves #565]

src/triage/cli.py
- Added new "private" method for load the configuration file using the `Storage.factory` method.
=> Fixes #598

requirement/main.txt, src/triage/component/postmodeling/contrast/model_evaluator.py
- Add postmodel requirements to requirement/main
- Change matrixstore references in postmodel.model_evaluator
=> Postmodel fixes

src/triage/cli.py
…variable `DATABASE_URL`
(In CLI.)
=> optionally read database connection information from process environment

docs/sources/experiments/running.md, src/tests/test_experiments.py, src/tests/test_partial_experiments.py, src/triage/cli.py, src/triage/experiments/base.py
Makes running config validation the default for both the class and CLI
=> Run validation by default [Closes #635]

docs/sources/dirtyduck/docs/choose_your_own_adventure.md, docs/sources/dirtyduck/docs/index.md, docs/sources/dirtyduck/docs/inspections.md, docs/sources/dirtyduck/org/00_instructions.org, docs/sources/dirtyduck/org/05_inspections.org, docs/sources/dirtyduck/org/choose_your_own_adventure.org, manage.py
=> Fixed broken links

requirement/include/test-management.txt, requirement/main.txt, src/triage/component/postmodeling/contrast/model_evaluator.py
=> normed -> density (Fixes #734)

dirtyduck/food_db/Dockerfile
=> Closes #715

docs/sources/experiments/cohort-labels.md, src/tests/timechop_tests/test_plotting.py, src/triage/cli.py, src/triage/component/catwalk/db.py, src/triage/component/catwalk/storage.py, src/triage/component/postmodeling/contrast/parameters.py, src/triage/component/postmodeling/contrast/utils/aux_funcs.py, src/triage/component/postmodeling/crosstabs.py, src/triage/component/results_schema/alembic/env.py, src/triage/experiments/defaults.py
NOTE: full_load supports the full YAML spec but it doesn't execute
arbitrary code.
=> load -> full_load (see https://msg.pyyaml.org/load for an explanation)

docs/sources/quickstart.md
The current introduction to label configuration in quickstart.md misses some important details.
This adds a deeper introduction to the purpose and requirements of the labels query. It also provides more context for the given example query.
=> Adds deeper introduction to label configuration in quickstart.md

docs/mkdocs.yml
Deactivates pymdownx.smartsymbols arrows option in mkdocs.yml
=> Fixes dependency graphs in Triage architecture docs [Closes #765]

src/tests/catwalk_tests/test_individual_importance.py, src/triage/component/catwalk/__init__.py, src/triage/component/catwalk/individual_importance/__init__.py, src/triage/experiments/base.py
=> Closes #643

docs/mkdocs.yml, docs/sources/api/timechop/index.md, docs/sources/api/timechop/plotting.md, docs/sources/api/timechop/timechop.md, src/triage/component/timechop/plotting.py, src/triage/component/timechop/timechop.py, src/triage/component/timechop/utils.py
- Implements Timechop API docs using MkDocstrings
- Progress on #778
=> Implement Timechop API docs

Dockerfile, dirtyduck/docker-compose.yml, src/triage/cli.py, tutorial.sh
=> Corrected some errors regarding the building of triage

dirtyduck/bastion/Dockerfile, dirtyduck/docker-compose.yml
=> No need to have a Dockerfile just for setting the PS1 variable

src/triage/component/catwalk/model_trainers.py, src/triage/component/catwalk/predictors.py
We've seen a warning message `Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1` in triage runs and wanted to explore this further. The issue here is the nested parallelization, with model types like random forest trying to use multiple jobs already within the multiprocessing we're doing in `triage`.
This draft PR explicitly uses a `threading` backend for both training and predicting and I had a couple of observations in initial testing:
- I had seen comments online about using `threading` potentially not actually yielding parallelization because of python's Global Interpreter Lock but I don't seem to encounter those issues here, so it seems perhaps RandomForests are releasing the lock in a way that allows threading to work.
- These changes do indeed get …
=> threading backend for model training and predictions
