MANIFEST.in
README.rst
requirements.txt
requirements_dev.txt
setup.py
triage/db.py

- Add stored procedure creation script to manifest
- Use __file__ to import correctly when imported as module
- Include requirements in setup.py
- Use new tagged collate
- Use https for tarball download
- Update README with usage

Make triage pipeline importable [Resolves #19]

---

triage/db.py

The connection pool was causing connection issues when getting a raw connection cursor in order to run the model group stored procedure. Disabling connection pooling by default seems to fix this without causing other problems.

Disable connection pooling [Resolves #22]

---

tests/test_model_trainers.py
tests/test_predictors.py
tests/test_storage.py
triage/model_trainers.py
triage/predictors.py
triage/storage.py

- Implement ModelTrainer.generate_trained_models as a generator interface for each trained model when grid training
- Implement Store.delete() for enable projects to clean up their stored models, either from storage or the references for garbage collection
- Implement Predictor.delete_model to make Store.delete() available from the model_id rather than the model hash (future: implement id-awareness into storage, or return hashes alongside ids from trainer?)

Allow yielding of trained models [Resolves #11]

---

example_experiment_config.yaml
requirements.txt
tests/test_integration.py
tests/test_pipeline.py
tests/test_scoring.py
triage/db.py
triage/pipeline.py
triage/scoring.py

- Remove evaluations.as_of_date and add evaluation_start_time, evaluation_end_time, prediction_frequency
- Save new evaluations fields for each test matrix that is evaluated
- Turn evaluation back on when multiple as-of-dates are present in a test matrix (i.e. inspections-style time splitting)

Support inspections-style evaluation [Resolves #54]

---

tests/test_feature_generators.py
tests/test_integration.py
tests/test_model_trainers.py
triage/feature_generators.py
triage/model_trainers.py
triage/pipeline.py

- ModelTrainer now takes MatrixStore at runtime, not initialization time
- Pipeline now instantiates all component objects at initialization time, calling them at runtime
- FeatureGenerator now takes in schema name
- Naming consistency changes in Pipeline

Instantiate pipeline components in constructor [Resolves #44]

---

tests/test_pipeline.py
triage/db.py
triage/pipelines/__init__.py
triage/pipelines/base.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py
triage/storage.py

- Create abstract class PipelineBase, which sets up components and requires subclasses to implement run
- Move current Pipeline to SerialPipeline, subclass of PipelineBase
- Create LocalParallelPipeline subclass of PipelineBase to spawn workers using concurrent.futures.ProcessPoolExecutor. Currently just parallelizing the testing phase
- Make poolclass configurable, as NullPool was giving some problems with multiple processes and QueuePool seems to be more robust
- Modify MettaCSVMatrixStorage to only load data upon use, improving serializability

Support parallelism [Resolves #28]

---

tests/test_feature_generators.py
triage/feature_generators.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py

- Refactor stripping of returned collate feature table names into FeatureGenerator
- Change stripping of feature table names to reflect recent changes where exclusion is performed in Python instead of SQL
- Remove tmp_entity_ids from exclusion tables because it doesn't exist at this point in the pipeline

Fix exclusion of feature aggregation tables [Resolves #66]

---

setup.py
triage/db.py

Two problems: 
1. triage.pipelines is now a subdirectory as of https://github.com/dssg/triage/pull/68 , which means to package it means that it needs its own entry in setup.py
2. We were getting problems with error messages coming from SQLAlchemy when using NullPool in a multi-process environment (ie, after pull 68 above). These seem to go away with QueuePool, so that should be the default in triage.db.connect() but still allow injection

Fix pipelines packaging, use QueuePool

---

example_experiment_config.yaml
tests/test_feature_generators.py
triage/feature_generators.py

- Add new feature categorical option, 'choice_query', which runs a query to determine a list of Collate `choices`
- Cache results of choice query in FeatureGenerator
- Add example of dynamic categorical to example_experiment_config.yaml

Dynamic Categorical Choices [Resolves #33]

---

tests/test_feature_dictionary_creator.py
tests/test_feature_generators.py
triage/feature_dictionary_creator.py
triage/feature_generators.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py

- Implement FeatureGenerator#_create_aggregation_tables, which reimplements SpacetimeAggregation.execute but bypassing aggregation tables for speed
- Return list of created feature tables from FeatureGenerator#generate
- Modify FeatureDictionaryCreator to take in a list of feature tables instead of querying information_schema for tables

Bypass collate aggregate tables [Resolves #76]

---

example_experiment_config.yaml
tests/test_feature_group_creator.py
tests/test_feature_group_mixer.py
triage/feature_group_creator.py
triage/feature_group_mixer.py
triage/features.py
triage/pipelines/base.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py

I've been trying this out on the feature_combinations timechop branch. I'm not sold on the names for any of these, suggestions welcome. And I'm not 100% sure this is the functionality that is needed, maybe we can work through a more real-world example as a test?
- Add FeatureGroupCreator to handle grouping a large feature dict by various criteria
- Add FeatureGroupMixer to handle combining of feature groups in different ways
- Use FeatureGroupCreator and Mixer in both pipelines, driven by configuration

Feature Groups [Resolves #50]

---

triage/pipelines/base.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py

- Introduce architect_factory to PipelineBase constructor, pre-binding all serializable parameters. This is to make instantiation of new Architects across process boundaries easier
- Use new Architect#generate_plans interface in both Serial and LocalParallel pipelines
- Run Architect#build_matrix tasks in parallel using concurrent.Futures in the LocalParallel pipeline

Support Parallelization of Matrix Creation [Resolves #81]

---

example_experiment_config.yaml
tests/test_feature_group_mixer.py
triage/feature_group_creator.py
triage/feature_group_mixer.py

- Rename 'all' feature group mixer strategy to the more accurate leave-one-in
- Create new 'all' feature group mixer strategy that smashes all groups into one feature dictionary
- Improve message of exception that is thrown when an unknown strategy is given
- Beef up docstrings

Add leave-one-in feature group mixer strategy [Resolves #88]

---

tests/test_feature_generators.py
triage/feature_generators.py
triage/pipelines/base.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py
triage/utils.py

- Introduce LocalParallelPipeline#parallelize to encapsulate parallelizing a function and list of tasks
- Rename high-level FeatureGenerator interface from 'generate' to 'create_all_tables'
- Add FeatureGenerator#aggregations for direct access to all collate Aggregations
- Add FeatureGenerator#generate_all_table_tasks to produce a parallelizable list of all tables and their creation/population queries
- Add FeatureGenerator#run_commands to run a list of SQL commands in a transaction
- Switch to multiprocessing.Pool to take advantage of chunksize
- In SerialPipeline, use new FeatureGenerator#create_all_tables
- In LocalParallelPipeline, retrieve all table tasks, and run inserts in parallel batches of 25

Parallelize Feature Generation [Resolves #83]

---

tests/test_scoring.py
triage/db.py
triage/scoring.py

- Sort and threshold the predictions with NaNs intact, and then remove the NaNs
- Add to the evaluations table the number of labeled examples, number of labeled examples above threshold, and number of positive labels. This will help the researcher make sense of different metrics.
- Add false positive rate metric

Fix evaluation of sparsely-labeled test matrices [Resolves #116]

---

tests/test_pipeline.py
triage/pipelines/local_parallel.py

- Adds n_db_processes to LocalParallelPipeline, to control how many processes are used for db-heavy phases (feature generation, testing and scoring)

Control number of database-connecting processes [Resolves #104]

---

tests/test_model_trainers.py
triage/model_trainers.py

- If n_jobs is sent in a parameter grid, don't include it in hash but do send it to the classifier

Remove n_jobs from parameters sent to model_hash [Resolves #126]

---

triage/model_trainers.py
triage/pipelines/base.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py

Information like lookback durations is tougher to include here because that info doesn't travel with the split, but this level of information is easy to provide.

Log more split info [Resolves #124]

---

tests/test_pipeline.py
triage/pipelines/local_parallel.py

- Modify LocalParallelPipeline#parallelize to include traceback on error
- Fix pipeline reuse test

Include traceback when child process errors [Resolves #140]

---

triage/pipelines/base.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py

- Introduce Pipeline#full_matrix_definitions to reduce complication when looping through them
- Loop through full_matrix_definitions when logging splits

Fix log split # denominator [Resolves #142]

---

example_experiment_config.yaml
tests/test_integration.py
tests/test_label_generators.py
tests/test_model_trainers.py
tests/test_pipeline.py
tests/test_predictors.py
tests/test_scoring.py
tests/test_utils.py
triage/db.py
triage/label_generators.py
triage/model_group_stored_procedure.sql
triage/model_trainers.py
triage/pipelines/base.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py
triage/predictors.py
triage/scoring.py
triage/utils.py

- Use new name of timechop.Inspections, timechop.Timechop
- Take in train_prediction_windows and test_prediction_windows, remove prediction_window and related hack
- Pass in train and test prediction windows to Timechop
- Generate labels for all prediction windows
- Use name 'train_durations' instead of 'look_back_durations'

Separate train/test prediction windows [Resolves #152]

---

tests/test_integration.py
tests/test_predictors.py
tests/test_storage.py
tests/utils.py
triage/pipelines/local_parallel.py
triage/pipelines/serial.py
triage/predictors.py
triage/storage.py
triage/utils.py

We want to make sure that when we process a prediction matrix, the columns match up with that of the train matrix. This turned out a bit more complicated than I wanted to, to keep some of the flexibility in triage.Storage (that is being used!).
When the InMemoryMatrixStore is used (example: https://github.com/dssg/police-eis/blob/master/eis/run_models.py#L306 ), it is impossible to infer anything about the train matrix. For that reason, we have to support the passing in of the column list itself. To handle this, we have an if statement in predictor.predict, that uses this when present but otherwise retrieves the column list by retrieving the train uuid, finding the stored matrix, and grabbing the column names from there. I don't love the end result, but I also can't think of a better …

Order prediction matrix columns to match train matrix [Resolves #170]

---

example_experiment_config.yaml
tests/test_experiments.py
triage/experiments/base.py

- Modify ExperimentBase to consider state_config to be optional
- Modify example_experiment_config.yaml to indicate that state config is optional
- Add tests to test_experiments to make sure that Experiments don't require state_config

Make state_config optional [Resolves #171]

---

example_experiment_config.yaml
tests/test_experiments.py
triage/experiments/__init__.py
triage/experiments/base.py

- Add experiments.CONFIG_VERSION to track the config version in the current code
- Add check at ExperimentBase construction time that ensures the config version matches the current one.
- Add config_version section to example_experiment_config.yaml
- Refactor experiment tests to share basic sample config

Version triage config files [Resolves #191]

---

.travis.yml
example_experiment_config.yaml
tests/test_experiments.py
triage/experiments/base.py

- Pass configured user_metadata key to Planner if it exists
- Add user_metadata to example_experiment_config.yaml

Pass User Metadata to Planner [Resolves #192]

---

example_experiment_config.yaml
requirements.txt
tests/test_experiments.py
triage/experiments/base.py

Here, support for collate's multiple-groups functionality is added by using the updated interface of architect.FeatureGenerator. It requires a list of collate aggregations. So here we add that list to the necessary calls and expose the collate_aggregations list as a property of the Experiment.
- Add Experiment#collate_aggregations
- Modify Experiment#feature_table_tasks and #feature_dicts to pass the collate aggregations
- Add multiple-groups example to example config and tests

Support collate groups [Resolves #188]

---

triage/experiments/base.py
triage/experiments/multicore.py
triage/experiments/singlethreaded.py

- Move state_table_generator.clean_up calls to finally block in base class
Note: We can't accomplish this using a temporary table because the states table has to live far longer than one database session.

Clean up States Table in finally block [Resolves #197]

---

example_experiment_config.yaml

Minor documentation updates for the additional rule to allow zero filling with no imputation flag in cases (such as event counts) where NULLs are known to be 0 exactly.

Support zero filling with no imputation flag

---

example_experiment_config.yaml
requirements.txt
tests/test_experiments.py
triage/experiments/__init__.py
triage/experiments/base.py
triage/experiments/multicore.py
triage/experiments/singlethreaded.py

Support imputation rules in collate/architect to allow users to specify how to handle missing data. See additional details in the related collate and architect PRs.

Imputation (Closes #196)

---

example_experiment_config.yaml

If merged, this commit will:
- update the key names in model group keys to use the actual names in matrix metadata
- unbutcher the sentence explaining the keys

Use accurate model group keys in example config [Resolves #225]

---

example_experiment_config.yaml
requirements.txt
tests/test_experiments.py
tests/utils.py
triage/experiments/__init__.py
triage/experiments/base.py
triage/experiments/multicore.py
triage/experiments/singlethreaded.py

Changes to support the new timechop names in [timechop pr 79](https://github.com/dssg/timechop/pull/79/)
NOTES: 
* several test failures but look like they're coming from `results-schema` not yet being updated
* still need to bump the pegged dependency versions once they're updated.
See also:
* https://github.com/dssg/metta-data/pull/49
* https://github.com/dssg/architect/pull/57
* https://github.com/dssg/catwalk/pull/36
* https://github.com/dssg/results-schema/issues/11

support new timechop names (closes #187)

---

docs/sources/experiments/algorithm.md
example_experiment_config.yaml
src/tests/architect_tests/test_integration.py
src/tests/architect_tests/test_state_table_generators.py
src/tests/test_experiments.py
src/tests/utils.py
src/triage/component/architect/state_table_generators.py
src/triage/experiments/base.py
src/triage/experiments/validate.py

The main goal of this PR is to allow the definition of cohorts with a query. It also includes a refactoring commit, to clean up and prepare the StateTableGenerator for the cohort changes. I'd probably recommend viewing each of these commits separately for clarity, or at least look at the new feature commit in isolation (it is much shorter than the refactoring).  I pasted both commit messages below for the details.
Allow defining cohort with a query [Resolves #333]
- Add StateTableGeneratorFromQuery class to generate a state table from a query, parameterized with a date, to return some set of entities that should be included for that date.
- Expose the new fubctionality at the 'query' key in cohort_config
- Update example experiment config, validator, and algorithm doc with new …

Cohort definition

---

src/triage/component/catwalk/individual_importance/uniform.py
src/triage/component/catwalk/model_trainers.py

Some classifiers do not support feature importance. For them, we write 
`Algorithm does not support a standard way to calculate feature importance.` into results.feature_importance as feature_name. This leads to problems when trying to write individual feature importance because the feature does not exist in the matrix. This PR checks for the fake feature name and sets the individual importances to Nulls.

inserting NULLs for individual feature importance - #361

---

docs/sources/experiments/algorithm.md
example_experiment_config.yaml
src/tests/architect_tests/test_feature_group_creator.py
src/tests/architect_tests/test_feature_group_mixer.py
src/tests/architect_tests/test_integration.py
src/tests/architect_tests/test_label_generators.py
src/tests/architect_tests/test_planner_builders.py
src/tests/catwalk_tests/test_integration.py
src/tests/catwalk_tests/test_model_grouping.py
src/tests/catwalk_tests/test_model_trainers.py
src/tests/catwalk_tests/utils.py
src/tests/test_experiments.py
src/tests/utils.py
src/triage/component/architect/feature_group_creator.py
src/triage/component/architect/feature_group_mixer.py
src/triage/component/architect/label_generators.py
src/triage/component/architect/planner.py
src/triage/component/catwalk/model_grouping.py
src/triage/component/catwalk/model_trainers.py
src/triage/experiments/base.py
src/triage/experiments/validate.py

There are a few related changes here, with the goal of making model grouping work more effectively, with a better set of default parameters, more customization, some additional types of information available to model grouping to make them more useful, and better documentation for how it works.
1. Cohort information:
It is useful to have the definition of the experiment's cohort present in the matrix metadata, both for manual inspection purposes but also model grouping. To do this, we add a 'name' attribute to the cohort_config section of the experiment definition.
- Update ExperimentBase to send cohort_config name to Planner
- Update example_experiment_config with cohort name
- Update experiment validation to receive a new 'name
2. Label information:
It's also useful to have label …

Overhaul model_group_keys

---

src/tests/architect_tests/test_builders.py
src/tests/architect_tests/test_integration.py
src/tests/architect_tests/test_planner.py
src/triage/component/architect/planner.py
src/triage/experiments/base.py
src/triage/experiments/multicore.py
src/triage/experiments/singlethreaded.py

Once upon a time, the Planner and Builder classes lived in one Timechop class called 'The Architect'. Eventually, the different functionalities (figuring out and deduping what matrices needed to be built, and then building matrices one-by-one) diverged into the two classes you see today, but to support backwards compatibility Planner delegated the building itself to Builder, as opposed to letting the Experiment have its own reference to a builder. This half-solution has lived on for far too long. We will be making much more changes in the builder soon, and it'll be easier to work on in its proper place.
- Remove builder delegation methods from Planner
- Create matrix builder in Experiment, and call build_matrix/build_all_matrices directly from experiments
- Split test_planner_builders …

Decouple Planner from Builder [Resolves #269]

---

src/tests/catwalk_tests/test_evaluation.py
src/triage/component/catwalk/evaluation.py

The code for generating evaluation metrics had a lot of common code in duplicated code paths that made it easy for bugs such as this to make it in: when a non-thresholded metric saw a null label, it would break.
- Refactor catwalk.evaluation to minimize the code duplication between absolute-thresholded, percentile-thresholded, and non-thresholded metrics so NaN labels affect all of them in the same way
- Add a test case for NaN labels sent to a non-thresholded metric

Fix NaN-label evaluation of non-thresholded metrics [Resolves #293]

---

src/triage/experiments/base.py

Instead of using a table simply called 'labels' for intermediate labels prior to matrix construction,
namespace it with the experiment hash. And clean it up after matrices are constructed.

Use experiment hash-namespaced labels table [Resolves #390]

---

docs/sources/experiments/running.md
src/tests/test_experiments.py
src/tests/test_partial_experiments.py
src/triage/component/architect/builders.py
src/triage/component/architect/database_reflection.py
src/triage/component/architect/feature_generators.py
src/triage/component/architect/feature_group_creator.py
src/triage/component/architect/label_generators.py
src/triage/component/architect/state_table_generators.py
src/triage/component/architect/utils.py
src/triage/component/catwalk/model_testers.py
src/triage/database_reflection.py
src/triage/experiments/base.py
src/triage/experiments/validate.py

- Modify various components and experiment itself to more gracefully handle missing configuration, sometimes adding checks where there are not but in some cases changing exception raising to warning
- Add cleanup boolean flag to experiment to control whether or not the temporary tables are cleaned up
- Tweak logging to make incremental output more clear
- Add partial_experiments test to ensure that incremental outputs will be available if only some configuration is sent
- Modify 'running parts of an experiment' section of experiment run doc with information about .run() and cleanup=False

Enable calling of .run() with only partial binding

---

src/tests/audition_tests/test_audition.py
src/triage/cli.py
src/triage/component/audition/__init__.py
src/triage/component/audition/distance_from_best.py
src/triage/component/audition/model_group_performance.py
src/triage/component/audition/plotting.py
src/triage/component/audition/regrets.py
src/triage/component/audition/selection_rule_performance.py

- An `Auditoin` class has two methods `run` and `validate`. 
- `run` is wrapping a series of `Auditioner`'s functionality like what we do with Audition in ipython notebook.
- `validate` is to validate the config file of audition like what validate in experiment. Currently not implemented.
- An basic cli commands for audition that takes `config` and `directory` as arguments. The `directory` is the location to store the figures and json files.
- Make all the plots in Audition storable locally. They will be using the `catwalk.storage` to store things more generally later.

Audition basic cli and files store

---

src/tests/audition_tests/test_audition.py
src/tests/audition_tests/test_thresholding.py
src/triage/component/audition/__init__.py
src/triage/component/audition/distance_from_best.py
src/triage/component/audition/thresholding.py

Add a new function `model_groups_filter` in `thresholding.py` to make sure that those model groups have different train end times won't make it to distance table. This will fix the confusion of seeing lots of model being filtered where there's no filter when we first call `plot_model_groups()` as well as the issue of non-existent best cases (#365 the gap of best cases in the plot before).

Audition model group filter

---

src/tests/architect_tests/test_builders.py
src/tests/architect_tests/test_integration.py
src/tests/architect_tests/test_planner.py
src/tests/architect_tests/utils.py
src/tests/catwalk_tests/test_evaluation.py
src/tests/catwalk_tests/test_individual_importance.py
src/tests/catwalk_tests/test_individual_importance_uniform.py
src/tests/catwalk_tests/test_integration.py
src/tests/catwalk_tests/test_model_trainers.py
src/tests/catwalk_tests/test_predictors.py
src/tests/catwalk_tests/test_storage.py
src/tests/catwalk_tests/utils.py
src/tests/test_experiments.py
src/tests/test_partial_experiments.py
src/tests/utils.py
src/triage/component/architect/builders.py
src/triage/component/architect/planner.py
src/triage/component/architect/utils.py
src/triage/component/catwalk/model_testers.py
src/triage/component/catwalk/model_trainers.py
src/triage/component/catwalk/predictors.py
src/triage/component/catwalk/storage.py
src/triage/experiments/base.py
src/triage/experiments/multicore.py

The Storage module needed some refactoring to allow different types of
data to come under the storage classes' purview. Matrix saving was
handled outside of the storage class in Experiments, which itself is a
problem but the problem will greatly expand in scope with the storing of
other artifacts like plots and notebooks. There were other
small problems, like the storage medium (s3/fs) logic being split
between two different class hierarchies.
To fix this, the Storage classes have been redesigned, a new one
(ProjectStorage) introduced, and the Experiment changed to use them
everywhere that storage is needed. The Storage changes were big enough
that many tests (particularly in catwalk, which already heavily used
Storage) broke in ways that were cumbersome to change one-by-one, and
some …

Refactor Storage, allow HDF support [Resolves #266]

---

src/tests/architect_tests/test_state_table_generators.py
src/triage/component/architect/state_table_generators.py

I reopened this issue (#408) because the same error happened in `architect`. Now the validation and `architect` behave exactly the same

Issue 408 reloaded

---

src/triage/cli.py
src/triage/util/db.py

This is the first step in order to close the issue #450 . At this moment it only loads the configuration file from CLI.
It would be nice to extend this in order to centralize the configuration of the db and the use of environment variables as suggested in #450.
In order to use it:
```
triage -dbfile database.yaml --setup my_triage_config.py
```
In `my_triage_config.py` for example you could connect a listener  in order to set a role in the connection to the database:
```
from sqlalchemy.event import listens_for
from sqlalchemy.pool import Pool
@listens_for(Pool, "connect")
def assume_role(dbapi_con, connection_record):
dbapi_con.cursor().execute('set role my_role;')
```

Added an argument for a pythonic entrypoint for setting an arbitrary initial configuration

---

src/triage/cli.py

The cmdmethod options on the Audition CLI seemed to be broken. This
commit brings the options to the constructor, similarly to the
Experiment CLI

Audition CLI fix [Resolves #463]

---

docs/sources/experiments/upgrade-to-v6.md
docs/sources/index.md
example_config.yaml
example_experiment_config.yaml
src/triage/experiments/__init__.py

This commit changes the config version to v6 and updates the documentation in response to changes to the interpretation of the `cohort_config`.

Change config to v6 [Resolves #468]

---

src/triage/cli.py

- Flip argument order in featuretest CLI to match documentation: "build
X feature for Y date"

Flip featuretest CLI arguments to match the doc [Resolves #486]

---

docs/sources/experiments/running.md
src/tests/architect_tests/test_label_generators.py
src/triage/component/architect/label_generators.py
src/triage/experiments/base.py

Make label generation respect the `replace` Flag. It only looks in the
same labels table it's using, which is experiment-namespaced, so it
won't often benefit from this, but it's a start.

Label Generation Replace Flag [Resolves #499]

---

src/tests/audition_tests/test_thresholding.py
src/triage/component/audition/thresholding.py

- The `model_group_filter` now is more flexible for the model groups and train end times that if the model's train end times contain the input `train_end_times` (no matter if it's by query or user input) , we let the model pass. In other words, the input `train_end_times` should be the same or a subset of models' train end times.
- In order to be verbose, the `model_group_filter` will raise an error if no models pass the filter.

Audition model group filter [Resovles #494]

---

docs/sources/experiments/running.md
requirement/main.txt
src/tests/catwalk_tests/test_utils.py
src/triage/component/catwalk/utils.py
src/triage/experiments/base.py
src/triage/experiments/multicore.py

Converts the MulticoreExperiment to use Pebble instead of
multiprocessing.
This allows us to wrap the ProcessExpired exception in the case of
the operating system (or something else) killing the subprocess. This
ensures the process pool can keep going and provide useful information
in the logs.

Prevent experiment hanging when worker is killed by OS [Resolves #501]

---

src/tests/architect_tests/test_feature_generators.py
src/tests/conftest.py

* a project-wide fixture, `db_engine`, provides the testing postgresql
database and the generic sqlalchemy connection engine with which to
query it, (and tears these down automatically)
* a test module-wide fixture, `test_engine`, extends `db_engine` with
database setup tasks, (replacing the module utility function,
`setup_db`)
* unittest.TestCase is replaced by a vanilla test class, such that test
class fixtures can be defined, (rather than xunit-style setUp)

added pytest fixtures to simplify and clean up (architect) tests

---

example_experiment_config.yaml
src/tests/collate_tests/test_collate.py
src/tests/collate_tests/test_imputations.py
src/triage/component/architect/feature_generators.py
src/triage/component/collate/collate.py
src/triage/component/collate/imputations.py
src/triage/util/pandas.py

Closes #502 
Added option `coltype` to `Aggregates` so you can specify the column type.
Besides that, the imputation makes some educated guesses about the type of the column `_imp` in particular is a `smallint`(*)
(*) I tried to use a `boolean` but the `COPY` to csv was storing an `f`/`t` instead of `0`/`1` ... :(

Closes #502

---

src/tests/catwalk_tests/test_predictors.py
src/triage/component/catwalk/predictors.py
src/triage/component/timechop/plotting.py
src/triage/experiments/validate.py

This PR adds:
- verbose output for the config validator to better check errors
- outputs the timechop figure to a png

Verbose config check

---

src/tests/test_experiments.py
src/triage/experiments/base.py
src/triage/experiments/multicore.py

The experiment checks whether or not the passed-in engine is a base sqlalchemy engine, and converts it into the serializable triage engine if so.
However, this check was broken. This PR fixes it to actually duck-type,
to see if the engine can be pickled to a memory file

Fix db engine check in Experiment [Resolves #538]

---

src/triage/component/architect/builders.py
src/triage/component/architect/feature_dictionary_creator.py
src/triage/component/architect/feature_generators.py
src/triage/component/architect/feature_group_creator.py
src/triage/component/architect/feature_group_mixer.py
src/triage/component/architect/utils.py
src/triage/component/catwalk/evaluation.py
src/triage/component/catwalk/predictors.py
src/triage/component/timechop/timechop.py
src/triage/util/structs.py

Long log lines are generally introduced by long lists of features or
as-of-times. Here we introduce structs to hold those lists but override
their __repr__ to be much shorter.
Some other minor logging issues are taken care of here, such as:
- one info->debug change
- change some from format-strings to logging arguments
- remove this one vestigial warning that had no purpose

Shorten log lines [Resolves #528]

---

src/tests/catwalk_tests/utils.py
src/tests/utils.py
src/triage/component/catwalk/model_grouping.py

In ModelGrouper, listify feature names so that even with the new shortened
string representation from #547 it still works.
The matrix metadata factories are also updated to reflect this.

Listify feature names in ModelGrouper [Resolves #551]

---

src/tests/catwalk_tests/test_storage.py
src/triage/component/catwalk/storage.py

*I.e.* clean-up / speculation for issue #530 and pull request #534
S3Fs *appears* to support the boto3 configuration necessary to set the
multipart upload threshold, (from the [API documentation](https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem) and from a
manual test I've just done).
Moreover, S3Fs appears to provide us a slightly nicer interface, and more
options for performance optimizations, than we could easily get on our
own, with so few lines of code. (For that matter, even as is, this means
fewer lines of code, and more straight-forward code.)
But … am I right?
See also: [my original comment](https://github.com/dssg/triage/pull/534#issuecomment-444218744)

support 5 GB multipart upload threshold via S3Fs

---

develop

The Bash library on which the `develop` script depends has been tweaked to better support non-GNU environments such as MacOS, (at least as far as I've been made aware that it needs to be).
…But, let me know how this works for you!
(If you check out this branch, you should be able to execute the script and … it should work.)
Resolves #532.

upgrade install-cli to better support non-GNU (MacOS)

---

docs/sources/experiments/running.md
src/tests/catwalk_tests/test_storage.py
src/tests/test_experiments.py
src/triage/cli.py
src/triage/experiments/base.py

- Add cProfile bindings to experiment.run, write to profiling_stats
directory in project path.
- Add local_fs_path method to Storage classes so modules that need a
filename to write to (e.g. cProfile) can still use Project Storage.
- Add cli option for profiling
- Add section on profiling to docs

 Experiment Profiling [Resolves #557]

---

example/config/experiment.yaml

To optimize speed for new users who are copying from the example
experiment config, we disable individual importance as that can take
some time

Disable individual importance in example experiment config

---

src/triage/component/results_schema/README.md
src/triage/component/results_schema/__init__.py

- Modify upgrade_db and stamp_db filename option to be filehandle option to match
what the CLI passes in
- Update README examples

Fix upgrade_db to use filehandle [Resolves #572]

---

src/tests/catwalk_tests/test_model_trainers.py
src/tests/catwalk_tests/test_storage.py
src/tests/conftest.py
src/triage/component/catwalk/__init__.py
src/triage/component/catwalk/individual_importance/__init__.py
src/triage/component/catwalk/model_trainers.py
src/triage/component/catwalk/predictors.py
src/triage/component/catwalk/storage.py
src/triage/component/catwalk/utils.py
src/triage/experiments/base.py
src/triage/experiments/multicore.py
src/triage/experiments/rq.py
src/triage/experiments/singlethreaded.py

Converts the 'train task' into 'train/test task', so instead of training
a split all at once and then testing it all at once, each model is
trained and then immediately tested. Additionally, the tasks are
flattened instead of grouped by split.
A cache is added to the ModelStorageEngine so that the predictor can load the memory model if it's there. The ModelTrainTester manually uncaches the model once it's done testing. I think this should work but is worth some memory testing to make sure there's no terrible memory leaks. I didn't get time to test this part out before vacation so we should make sure to test that before merging.

Colocate Testing with Training [Resolves #560]

---

src/tests/catwalk_tests/test_storage.py
src/triage/component/catwalk/storage.py

Pandas' read_hdf does not implement a method for only loading the first
n rows that works reliably on different datasets, particularly with multi-indices.
This is problematic because head_of_matrix is how the MatrixStore
implements empty() and columns() methods.
Instead of implementing head_of_matrix, we implement
empty() and columns() on HDFStore directly, obviating the need for a
head_of_matrix method that only reads the first row.

Fix empty/columns check on HDFStore [Resolves #589]

---

src/triage/cli.py

Related to #512.
Doesn't show the plot, but it stores it to disk

Stores Timechop image to disk

---

example/config/audition.yaml

- Update the Audition config file with `model_metadata`
- Current the Audition config file only support one parameter-metric pair, but it supports multiple parameter-metric pairs if we use it interactively in python.

Audition config correct

---

docs/mkdocs.yml
docs/sources/experiments/upgrading.md
docs/sources/index.md

- Add audition reference to documentation sidebar and index [Resolves
- Add postmodeling reference to documentation sidebar and index
[Resolves #490]
- Add dirtyduck reference to documentation sidebar and index
- Move experiment upgrade links to own doc
- Rewrite index, remove some things that are now covered in other docs
(e.g. design goals, now in architecture doc)

Add Audition, Postmodeling, Dirty Duck references to docs

---

src/tests/catwalk_tests/test_storage.py
src/tests/test_partial_experiments.py
src/triage/component/catwalk/storage.py

- Make the CSVMatrixStore use compression and rename files to csv.gz

Use compressed CSVs [Resolves #498]

---

src/triage/component/catwalk/__init__.py
src/triage/component/catwalk/storage.py

Generating train/test tasks can take hours. One culprit may be slow IO
of the matrices, which are loaded to decide if the job should be
processed. This commit makes the train-tester generate all of the tasks
withoug checking the matrices and skips processing the tasks if the
matrices are no good.

Faster train/test task generation

---

src/triage/experiments/validate.py

Adds a validation for feature group prefixes to ensure they're distinct, as we've noticed that overlapping prefixes (e.g., `mh` and `mh_dx`) cause problems with some subset strategies, such as leave-one-out. 
Note that we should be able to remove this validation when the underlying bug is fixed, but seemed like a useful stop-gap in the meantime.

Validate distinct feature group prefixes

---

src/triage/cli.py
src/triage/component/results_schema/README.md
src/triage/component/results_schema/__init__.py

- Replace db_config_filehandle support in results_schema utilities with
dburl and pass dburl from standard Triage CLI parsing options

Enable dburl env var in results_schema CLI [Resolves #636]

---

src/tests/conftest.py
src/tests/postmodeling_tests/test_without_predictions.py
src/triage/component/postmodeling/contrast/model_evaluator.py
src/triage/component/postmodeling/contrast/model_group_evaluator.py

A quick fix to make the behavior in postmodeling more understandable if
it is run following an experiment without predictions.
- No longer use predictions to populate regular metadata
- When predictions are retrieved, throw an error if predictions are
empty
- Modify the repr to no longer use computed data from the database

Harden postmodeling against lack of predictions [Resolves #638]

---

src/triage/component/postmodeling/contrast/postmodeling_tutorial.ipynb

Import postmodeling utilities from installed `triage` rather than assuming notebook is being run in postmodeling code directory for example notebook.

fix imports in example postmodeling notebook

---

src/triage/component/catwalk/feature_importances.py

This commit adds a small change into the catwalk component to calculate feature importances when the model object is a `catwalk.estimators.ScaledLogisticRegression`. Now, instead of not
calculating anything, triage will be able to push  to the `feature_importances` db table the importances using the marginal change of the coefficients (using the exponential function). This solves the old #509.

Add feature_importance metric to SLR [solves #509]

---

.travis.yml
CONTRIBUTING.md
manage.py

- Fixes the travis pypi deploy
- Adds a travis github pages deploy and a manage command to run the
local documentation site

Fix Travis deploy [Resolves #493]

---

requirement/main.txt

Ohio has had some speed upgrades since we've started using it, and 0.1.2 is ancient in ohio terms, so this PR upgrades it.

Upgrade ohio

---

src/tests/catwalk_tests/test_integration.py
src/triage/component/catwalk/__init__.py

A bug was introduced when the train/test matrix checking switched from "create task" to "process task", in that the log messages were using variables that didn't actually exist. This snuck by because empty splits don't actually happen very often, but eventually we did run into it in production.
This fixes the bug, adds a test for it, and additionally moves those checks in the cache block to minimize unnecessary re-downloading of the matrix.

Fix logging typos that only show up when splits are empty

---

.travis.yml
docs/sources/dirtyduck/docs/eis.md
docs/sources/dirtyduck/docs/inspections.md
docs/sources/dirtyduck/docs/triage_intro.md
docs/sources/dirtyduck/org/index.md
docs/sources/experiments/running.md
requirement/main.txt
setup.py
src/tests/architect_tests/test_builders.py
src/tests/architect_tests/utils.py
src/tests/catwalk_tests/test_storage.py
src/tests/catwalk_tests/utils.py
src/tests/test_experiments.py
src/triage/cli.py
src/triage/component/architect/utils.py
src/triage/component/catwalk/storage.py
tox.ini

To support Python 3.7, remove the HDFMatrixStore (CSVs are compressed now, we get no real use out of HDF) and remove the ancient pytables dependency. Also update many documents and tests to remove HDF references.

Support Python 3.7 [Resolves #683]

---

src/tests/catwalk_tests/test_storage.py
src/tests/utils.py
src/triage/component/catwalk/storage.py

Underlying library ``s3fs`` automatically writes objects to S3 in "chunks"
or "parts" -- *i.e.* via multipart upload -- in line with S3's *minimum*
limit for multipart of 5 MiB.
This should, in general, avoid S3's *maximum* limit per (part) upload of
5 GiB. **However**, ``s3fs`` assumes that no *single* ``write()`` might
exceed the maximum, and as such fails to chunk out such too-large upload
requests prompted by singular writes of 5+ GiB.
This can and should be resolved in ``s3fs``. But first, it can, should
be and is resolved here in ``S3Store``.
resolves #530
In addition to the included unit test, a functional test script was composed – currently uploaded to Gist as [test_store.py](https://gist.github.com/jesteria/079df79e0e591209aa6028053d720426).
In its default, incremental mode, the …

write 5+ GiB (matrices) to S3Store

---

src/tests/results_tests/test_upgrade_if_clean.py
src/triage/component/results_schema/__init__.py
src/triage/experiments/base.py

To avoid the problem of time-consuming database upgrades happening when
we don't want them, the Experiment now:
1. Checks to see if the results_schema_versions table exists at all. if
it doesn't exist, upgrade. This is because means the results schema
should be clean in this case, and new users won't have to always run a
new thing when they first try Triage.
2. If it does exist, and the version number doesn't match what the
code's current HEAD revision is, throw an error. The error message is
customized to whether the database revision is a known revision to the
code (easy case, just upgrade if you have time) or not (you probably
upgraded on a different branch and need to go check out that branch to
downgrade).

Don't auto-upgrade db for new Experiments [Resolves #695]

---

src/triage/cli.py
src/triage/component/results_schema/__init__.py

In recent weeks/months, more operations on the results schema have
proven to be things that are useful to 'users' (people who use the
'triage' command), not just 'developers' (people who use the 'manage'
command). These include: stamping to a specific revision, downgrading,
upgrading to a specific revision, and even just viewing the revision history.
Here we allow the `triage db` command to interface with
alembic to do these things.
Furthermore, the old 'stamp' logic in `triage db` isn't terribly useful
now that we have been on alembic for a while, and pinning it to
experiment config versions wasn't very useful. Using the standard
alembic revisions for stamping I think makes more sense, but I copied
the dictionary from before into the help text for 'stamp' because it
could still be …

Add more user database management options to CLI [Resolves #697]

---

src/triage/component/catwalk/evaluation.py

This PR fixes an error encountered when running triage with no bias config, however, there may be a better approach here to ensuring we're consistently passing around either an empty dataframe or `None`, so we might want to revisit later.

Fix error with no bias config [Closes #706]

---

MANIFEST.in

WIth the new defaults schema, `model_grid_presets.yaml` should be included in the installation

Update MANIFEST.in to include presets

---

src/triage/cli.py

The current CLI behavior falls back to the `DATABASE_URL` environment variable before checking for `database.yaml` in its default location. However, this doesn't quite line up with our documentation and could create unexpected behavior, especially for users with multiple triage projects or who have the environment variable set for other reasons.

check for default db config file before falling back to env var

---

src/triage/component/catwalk/feature_importances.py

Some models returning a single feature importance value (e.g., logistic regressions with one feature) were returning a scalar rather than an array, causing catwalk to fail when trying to write these models to the database and no predictions to be produced. This is in particular an issue with our new QuickStart Guide and Dirty Duckling Tutorial.
This PR simply checks the results for scalar values and reshapes them into an array with length of 1.

fix feature_importances bug with single-coefficient models

---

docs/sources/experiments/experiment-config.md

Adding a little more context about why `user_metadata` exists and on what the example use case is for. Plus voice consistency.

[closes #811] improve user_metadata documentation

---

.github/workflows/test.yaml

Travis doesn't appear to be working right now, so I got the test suite going with Github actions. This doesn't include PyPI upload or documentation site upload, but I think we can do those in a separate pull request. Now that we're doing a Triage sprint, having something automatically run our tests seems pretty high value, so I'd rather get this merged ASAP for the benefit of the sprint.

GitHub action test

---

requirement/dev.txt
requirement/main.txt
src/tests/architect_tests/test_integration.py
src/triage/component/catwalk/storage.py

Updates PyYAML and mkdocs-material to satisfy safety-ci
However, note that for loading matrix metadata I'm switching from `yaml.full_load(fd)` to `yaml.load(fd, Loader=yaml.Loader)` which isn't ideal. Based on the errors I was getting, it seems that in order to stick with `full_load`, we would need to define representers and constructors specifically for the `AsOfTimeList` and `FeatureNameList` (see the [example here](https://pyyaml.org/wiki/PyYAMLDocumentation)). Note that doing so would lose the ability to load matrix metadata from previous versions of triage (though a utility to upgrade old metadata files probably wouldn't be too difficult to write).
@thcrock -- would appreciate your thoughts here.

Dependency updates

---

docs/sources/triage_project_workflow.md
example/config/experiment.yaml
src/tests/test_defaults.py
src/triage/experiments/defaults.py

Allow users to specify both `model_grid_preset` and `grid_config` sections of the experiment config, combining the unique model types and specifications across them. In general, I think this will be most useful when you want to add project-specific baselines on top of the preset grid.

Allow specifying both preset and user-specified model grids

---

src/tests/test_experiments.py
src/tests/utils.py

Fixes a small bug that was causing an exception on test cleanup on some systems by explicitly closing DB sessions when we're done with them.

Small bugfixes for errors on test cleanup

---

.github/workflows/test.yaml
requirement/main.txt
src/tests/catwalk_tests/test_integration.py
src/triage/component/catwalk/__init__.py

Removes Python3.6 support and adds up to 3.9.
Changes needed:
- numpy upgrade
- Removes create_autospec function call from catwalk integration test; it appears that simply passing the class name to spec_set works now, and create_autospec used in conjunction with this now breaks it.

Issue 864 py39

---

src/tests/catwalk_tests/test_protected_groups_generators.py
src/triage/component/catwalk/protected_groups_generators.py

Closes #875 -- quick PR to ensure all attribute columns are read as strings rather than numeric datatypes when constructing the protected_df (numeric columns will cause downstream errors with the aequitas crosstabs).

Ensure attribute columns are strings in protected_df (closes #875)

---

.github/workflows/test.yaml
requirement/main.txt
src/tests/conftest.py

Upgrade `wrapt` package to 1.13.3 to fix the issue #863.

update wrapt version

---

src/triage/component/results_schema/alembic/versions/3ce027594a5c_add_hashes_to_runs.py
src/triage/component/results_schema/schema.py
src/triage/experiments/base.py
src/triage/predictlist/__init__.py
src/triage/tracking.py

Closes #859 
Currently, the relationship between a given run and the labels table/hash, cohort table/hash, and bias hash isn't stored anywhere (aside from the logs), which can make debugging and iterating on the experiment config a bit challenging. To address this, the current pull request adds tracking of these associations to the `triage_runs` table.

Add information about cohort, label, and bias to triage_runs

---

src/tests/architect_tests/test_database_reflection.py
src/tests/architect_tests/test_label_generators.py
src/tests/postmodeling_tests/test_add_predictions.py
src/tests/test_database_reflection.py
src/triage/component/architect/entity_date_table_generators.py
src/triage/component/architect/label_generators.py
src/triage/component/architect/validations.py
src/triage/database_reflection.py

Closes #872 
Adds a check for duplicates in the labels or cohort table in order to error earlier and with a more helpful message when this occurs (currently, this tends to cause a duplicate primary key error far downstream when saving predictions, which can be difficult to debug).
Note that I actually haven't added a unit test for catching duplicates in the cohort because two routes (via query or labels) for generating these already do a `distinct` or `group by` so these shouldn't actually occur. We could consider removing this logic and putting the burden on user (which might enforce better understanding of what triage is doing/expecting), but I'm not sure that's too worthwhile.
@thcrock -- is the fact that there are two (essentially identical) `database_reflection.py` files (one in …

Error on cohort or label duplicates

---

example/config/experiment.yaml

The example experiment had two cohort sections. Only one is needed.

Remove duplicate cohort section

---

src/triage/experiments/validate.py

Quick PR to fix an error @rayidghani encountered on running with a `groups` key in the feature config -- this should now raise the intended deprecation warning rather than a cryptic error. We should also add a unit test for this behavior at some point (I created an issue to that effect), but I wanted to go ahead and merge this quickly to fix the bug.

Fix bug in check for collate groups key

---

src/tests/test_defaults.py
src/triage/component/architect/entity_date_table_generators.py
src/triage/experiments/base.py
src/triage/experiments/defaults.py
src/triage/experiments/validate.py

Somewhat urgent bugfix -- currently, when omitting the `cohort_config` section of a `triage_config`, it gets filled in with a default query that selects all `entity_id` values from the feature table from objects. However, this default behavior no longer applies because this section of the config is now optional.
To fix this issue, this pull request does three things:
- Remove the `fill_cohort_config_missing` default function (and associated test)
- Allows for passing the `CohortConfigValidator` if the `cohort_config` section is omitted
- Avoids inserting cohort records for `as_of_date` values that already exist in the cohort table when defining the cohort based on the labels table (note directly related to the bugfix, but avoids potential inconsistencies by mimicking the existing behavior …

Bugfix for obtaining cohort from labels table

---

src/triage/component/architect/entity_date_table_generators.py

Need to unpack the results list for the log message when encountering existing as_of_dates in the cohort table and building from the labels query while using `replace=False`

Fix bug with logging existing cohort dates

---

docs/sources/experiments/temporal-validation.md

Couldn't find anything on the chop_time() method of chopper in the docs - thought it was worth adding because sometimes the visualize_chops() plot can be hard to read

adding docs about chop_time method

---

.github/workflows/test.yaml

`testing.postgresql` runs `initdb` locally. The postgres service doesn't get used.

Remove postgres service from github action [Resolves #899]

---

src/triage/predictlist/__init__.py
src/triage/predictlist/utils.py

The `predictlist` module needs to be updated to work with the current version of triage. This PR deals with the case of predicting with an existing model as it is a near-term priority, but will need to update the `Retrain` class as well:
Makes the following updates:
- handle the case where an explicit cohort is not defined by inferring the cohort from the label query
- handle the case where there's an overlap in feature group prefixes. e.g., when there are two feature groups `eviction` and `eviction_cases`, the features from the latter were included in the former leading to errors. 
- Fix the error with matrix metadata creation
- Handle the case with no `user_metadata` defined

Updating predict forward with existing model

---

src/triage/component/architect/builders.py
src/triage/predictlist/__init__.py

Modify the `builders.py` component to deal with the use case of not having labels on the matrix (predict forward). In case there are no labels, a CSV file is generated with 0s in it.  This change follows the logic on tag 5.2.3.  
It was tested with DoJo data using the `predictlist` logic: 
- Using only the `predict_forward_with_existed_model`
- Using the `Retrainer` object with `retrain` and `predict` methods

Lm predict forward no labels in matrix

---

src/tests/architect_tests/test_entity_date_table_generators.py
src/triage/component/architect/entity_date_table_generators.py
src/triage/component/catwalk/subsetters.py
src/triage/experiments/base.py

In the current version of triage, we view `subsets` as subsets of entities independent from cohorts we create (unless we add the cohort query to the subset query). As a result, the subset tables tend to have duplicates of the same entity_id for many as of dates (even if those entities are not a part of the cohort for those as of dates) and tends to create very large tables. 
This is more acute when we have a large universe of entities. To counter this, either we could include the cohort query in every subset query we write on the experiment config (e.g., as a CTE), or we could modify it under the hood to only include entities from the respective cohorts into the subset (treating subsets as a subset of a cohort rather than a subset of all entities). This PR is attempting to do the latter. …

Changing how we create subsets 

---

src/tests/catwalk_tests/test_baselines.py
src/triage/component/catwalk/baselines/rankers.py

Adding a Linear Ranker to the menu of options of simple baselines Triage offers. 
The Capstone 2023 team developed this linear ranker as a way to emulate a heuristic generated by one of our partners in the DoJo project. It uses a list of features and corresponding weights to generate a weighted sum of features.
Unit tests were also generated (and tested).
Closes issue #961

Add linear ranker to Triage

---

.github/workflows/build-mkdocs.yaml
README.md
docs/mkdocs.yml
docs/sources/api/audition/auditioner.md
docs/sources/api/audition/selection_rules.md
docs/sources/api/timechop/plotting.md
docs/sources/api/timechop/timechop.md
docs/sources/dirtyduck/index.md
docs/sources/postmodeling/index.md
requirement/dev.txt
requirement/main.txt
src/tests/catwalk_tests/test_baselines.py
src/triage/cli.py
src/triage/component/catwalk/baselines/rankers.py

* Added `LinearRanker` to the available options for simple rankers. This ranker allows users to define weighted features, enabling the creation of baseline models that can mimic existing solutions
* Fixed the path for `add_predictions` script on CLI 
* Added `jupyter` package to requirements. The Experiment Summary Report task added in version 5.4.0 requires `ipykernel` and `nbconvert`, which come as part of the `jupyter` package
* Fixed display precision option in the experiment summary report template notebook
* Updates in the Postmodeling section documentation on github pages 
Closes issues #960 #962

Linear ranker and CLI fix

---

src/triage/component/architect/builders.py
src/triage/component/architect/utils.py
src/triage/component/catwalk/storage.py

Closes Issue #957 
When the project's storage is S3, we use the `/tmp` folder to store temporary files needed to build feature matrices and to download the matrices stored in S3 when training models. `csv.gz` files weren't being deleted, causing problems when more than 1 person is working on the same project. Now we use the `/tmp/{user}` folder to store files generated by Triage, making sure we are deleting them after feature matrices creation **and** after we upload the matrices in memory for training models.  
* `catwalk.storage`: Using `/tmp/{user}` to store temporary CSV files, matrices generated (`csv.gz`), and matrices downloaded from S3 used for training.
* `architect.builders`: 
* Eliminated `generate_gzip` and `remove_unnecessary_files` functions from the MatrixBuild class and …

Deleting matrices (csv.gz) from /tmp when using S3 as storage

---

example/label/events.sql

In general, we try to use `>=` and `<` rather than `<=` or `>` for time inequalities in our examples to be consistent with the fact that triage internally uses closed-left-ends and open-right-ends for time intervals. This makes mentally translating examples into triage behavior easier. This commit fixes an example where we used `<=` for label creation.

use >=, not <=

---

requirement/test.txt
src/tests/postmodeling_tests/test_crosstabs.py
src/tests/utils.py
src/triage/component/architect/builders.py
src/triage/component/architect/utils.py
src/triage/component/postmodeling/crosstabs.py

Adds a function to `crosstabs.py` for generating crosstabs from the saved matrix without having to rely on the `features` schema. When trying to add tests to the testing suite, had to make a couple of additional changes. 
- If the project folder is an S3 bucket, when we create matrices, we use a /tmp folder to store temporary matrices. Then, once the matrices are moved to S3, we delete the files in the /tmp folder. In the test suite, the mock experiment uses a /tmp folder as the `project_folder`, and our current process would delete everything from the project folder, removing the matrices needed for model building. To fix this, this PR passes an explicit s3 flag to the `remove_unnecessary_files()` without relying on the path starting with `/tmp`. This change affects triage experiments, …

Crosstabs from a matrix
